apply plugin: 'com.android.application'

android {
    namespace "com.ferbersleeptimer.babytracker"
    compileSdk 35

    signingConfigs {
        release {
            if (project.hasProperty('MY_APP_UPLOAD_STORE_FILE')) {
                storeFile file(MY_APP_UPLOAD_STORE_FILE)
                storePassword MY_APP_UPLOAD_STORE_PASSWORD
                keyAlias MY_APP_UPLOAD_KEY_ALIAS
                keyPassword MY_APP_UPLOAD_KEY_PASSWORD
            }
        }
    }

    defaultConfig {
        applicationId "com.ferbersleeptimer.babytracker"
        minSdk rootProject.ext.minSdkVersion
        targetSdk 35
        versionCode 2
        versionName "1.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar', '*.include'], dir: 'libs')
    implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"
    implementation "androidx.coordinatorlayout:coordinatorlayout:$androidxCoordinatorLayoutVersion"
    implementation "androidx.core:core-splashscreen:$coreSplashScreenVersion"
    implementation project(':capacitor-android')
    testImplementation "junit:junit:$junitVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidxExtJunitVersion"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"
}

try {
    def googleServicesJSON = file('google-services.json')
    if (googleServicesJSON.exists()) {
        apply plugin: 'com.google.gms.google-services'
    }
} catch (Exception e) {
    logger.info("google-services.json not found, google-services plugin not applied.")
}
